INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Access floor'),
	 ('Acoustic flocking'),
	 ('Actuator'),
	 ('Aggregation WDM (Wavelength Division Multiplexing)'),
	 ('Aggregation router'),
	 ('Air conditioning group 0.8 MW'),
	 ('Air insulated switchgear envelope'),
	 ('Air insulated switchgear module'),
	 ('Alarm'),
	 ('Alimentation externe ordinateur portable');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Alimentation externe smartphone et tablette'),
	 ('Articulated lorry transport Euro 0, 1, 2, 3, 4 mix 40 t total weight, 27 t max payload RER'),
	 ('BBU 2G-5G (BTS, NODEB, ENODEB and GNODEB) one card'),
	 ('Backbone WDM (Wavelength Division Multiplexing)'),
	 ('Backbone network EU-28'),
	 ('Backbone network FR'),
	 ('Ballasted column 400 mm diameter'),
	 ('Barcode scanner'),
	 ('Barrier'),
	 ('Baseboard wood');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Basement wall'),
	 ('Bituminous primer'),
	 ('Blade server  1 processor high-end  1 SSD: 1024 GB each  0 HDD  16 RAM, 16 GB each  0 GPU'),
	 ('Blade server  1 processor high-end  1 SSD: 1024 GB each  0 HDD  2 RAM, 16 GB each  0 GPU'),
	 ('Blade server  1 processor high-end  1 SSD: 1024 GB each  0 HDD  2 RAM, 4 GB each  0 GPU'),
	 ('Blade server  1 processor high-end  1 SSD: 1024 GB each  0 HDD  24 RAM, 16 GB each  0 GPU'),
	 ('Blade server  1 processor high-end  1 SSD: 1024 GB each  0 HDD  48 RAM, 16 GB each  0 GPU'),
	 ('Blade server  1 processor high-end  1 SSD: 1024 GB each  0 HDD  48 RAM, 64 GB each  0 GPU'),
	 ('Blade server  1 processor high-end  1 SSD: 1024 GB each  0 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Blade server  1 processor high-end  4 SSD: 2048 GB each  0 HDD  16 RAM, 16 GB each  0 GPU');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Blade server  1 processor high-end  4 SSD: 2048 GB each  0 HDD  2 RAM, 16 GB each  0 GPU'),
	 ('Blade server  1 processor high-end  4 SSD: 2048 GB each  0 HDD  2 RAM, 4 GB each  0 GPU'),
	 ('Blade server  1 processor high-end  4 SSD: 2048 GB each  0 HDD  24 RAM, 16 GB each  0 GPU'),
	 ('Blade server  1 processor high-end  4 SSD: 2048 GB each  0 HDD  48 RAM, 16 GB each  0 GPU'),
	 ('Blade server  1 processor high-end  4 SSD: 2048 GB each  0 HDD  48 RAM, 64 GB each  0 GPU'),
	 ('Blade server  1 processor high-end  4 SSD: 2048 GB each  0 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Blade server  1 processor low-end  0 SSD: 0 GB each  1 HDD  2 RAM, 16 GB each  0 GPU'),
	 ('Blade server  1 processor low-end  0 SSD: 0 GB each  1 HDD  2 RAM, 4 GB each  0 GPU'),
	 ('Blade server  1 processor low-end  0 SSD: 0 GB each  1 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Blade server  1 processor low-end  0 SSD: 0 GB each  4 HDD  2 RAM, 16 GB each  0 GPU');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Blade server  1 processor low-end  0 SSD: 0 GB each  4 HDD  2 RAM, 4 GB each  0 GPU'),
	 ('Blade server  1 processor low-end  0 SSD: 0 GB each  4 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Blade server  1 processor low-end  1 SSD: 1024 GB each  0 HDD  2 RAM, 16 GB each  0 GPU'),
	 ('Blade server  1 processor low-end  1 SSD: 2048 GB each  0 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Blade server  1 processor low-end  2 SSD: 1024 GB each  0 HDD  2 RAM, 16 GB each  0 GPU'),
	 ('Blade server  1 processor low-end  2 SSD: 2048 GB each  0 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Blade server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  16 RAM, 16 GB each  0 GPU'),
	 ('Blade server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  16 RAM, 16 GB each  1 GPU'),
	 ('Blade server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  2 RAM, 16 GB each  0 GPU'),
	 ('Blade server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  2 RAM, 16 GB each  1 GPU');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Blade server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  2 RAM, 4 GB each  0 GPU'),
	 ('Blade server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  2 RAM, 4 GB each  1 GPU'),
	 ('Blade server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  24 RAM, 16 GB each  0 GPU'),
	 ('Blade server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  24 RAM, 16 GB each  1 GPU'),
	 ('Blade server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  48 RAM, 16 GB each  0 GPU'),
	 ('Blade server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  48 RAM, 16 GB each  1 GPU'),
	 ('Blade server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  48 RAM, 64 GB each  0 GPU'),
	 ('Blade server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  48 RAM, 64 GB each  1 GPU'),
	 ('Blade server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Blade server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  8 RAM, 16 GB each  1 GPU');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Blade server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  16 RAM, 16 GB each  0 GPU'),
	 ('Blade server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  16 RAM, 16 GB each  1 GPU'),
	 ('Blade server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  2 RAM, 16 GB each  0 GPU'),
	 ('Blade server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  2 RAM, 16 GB each  1 GPU'),
	 ('Blade server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  2 RAM, 4 GB each  0 GPU'),
	 ('Blade server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  2 RAM, 4 GB each  1 GPU'),
	 ('Blade server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  24 RAM, 16 GB each  0 GPU'),
	 ('Blade server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  24 RAM, 16 GB each  1 GPU'),
	 ('Blade server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  48 RAM, 16 GB each  0 GPU'),
	 ('Blade server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  48 RAM, 16 GB each  1 GPU');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Blade server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  48 RAM, 64 GB each  0 GPU'),
	 ('Blade server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  48 RAM, 64 GB each  1 GPU'),
	 ('Blade server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Blade server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  8 RAM, 16 GB each  1 GPU'),
	 ('Blade servers power supply'),
	 ('Buried insulation'),
	 ('Buried pipeline'),
	 ('Cable Cat 6a'),
	 ('Cable Serial bus'),
	 ('Cable multipair');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Cablofil'),
	 ('Capacitive touchscreen LCD display panel, color, high-tech application'),
	 ('Capacitive touchscreen OLED display panel, color'),
	 ('Cash-desk printer'),
	 ('Casing mix of equipment'),
	 ('Central intrusion alarm'),
	 ('Centralized technical management (CTM)'),
	 ('Collection router'),
	 ('Computer monitor 24 inches, LCD'),
	 ('Computer monitor 28 inches, LCD');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Computer monitor 39 inches, OLED'),
	 ('Concrete gutter'),
	 ('Concrete slab'),
	 ('Connected device (IoT) Auto - Appliances'),
	 ('Connected device (IoT) Auto - Audio'),
	 ('Connected device (IoT) Auto - Cooking'),
	 ('Connected device (IoT) Auto - Lighting'),
	 ('Connected device (IoT) Auto - Space'),
	 ('Connected device (IoT) Auto - Street lights'),
	 ('Connected device (IoT) Auto - Water heating');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Connected device (IoT) Blinds + windows'),
	 ('Connected device (IoT) Comm building control'),
	 ('Connected device (IoT) Gateway - Bus'),
	 ('Connected device (IoT) Gateway - LE to WiFi'),
	 ('Connected device (IoT) Security - Control'),
	 ('Connected device (IoT) Security - Video'),
	 ('Connected device (IoT) Sensors - Health'),
	 ('Connected device (IoT) Sensors - Industry'),
	 ('Connected device (IoT) Sensors - Res-LE'),
	 ('Connected device (IoT) Sensors - Res-WiFi');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Connected device (IoT) Smart meters'),
	 ('Connected speaker'),
	 ('Connector RJ45'),
	 ('Container ship ocean technology mix 27.500 dwt pay load capacity RER'),
	 ('Copper braiding (grounding)'),
	 ('Copper cable'),
	 ('DSLAM (Digital Subscriber Line Access Multiplexer)'),
	 ('DVD-ROM Drive'),
	 ('Desktop 1 CPU 126 mm² 14 nm lithography, 4 GB RAM, 256 GB SSD, integrated graphic card'),
	 ('Desktop 1 CPU 149.6 mm² 14 nm lithography, 8 GB RAM, 1000 GB HDD, 256 GB SSD, separated graphic card 363 mm² 28 nm lithography');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Desktop 1 CPU 180 mm² 14 nm lithography, 8 GB RAM, 1000 GB HDD, 256 GB SSD, separated graphic card 363 mm² 28 nm lithography'),
	 ('Desktop 1 CPU 192 mm² 14 nm lithography, 16 GB RAM, 2000 GB HDD, 1024 GB SSD, separated graphic card 363 mm² 28 nm lithography'),
	 ('Desktop 1 CPU 192 mm² 14 nm lithography, 16 GB RAM, 2000 GB HDD, 512 GB SSD, separated graphic card 363 mm² 28 nm lithography'),
	 ('Diesel oil combustion in engine, including diesel oil production consumption mix, at consumer 42 MJ/kg net calorific value RER'),
	 ('Diesel oil production mix, at plant RER'),
	 ('Digital price tag - Power unit'),
	 ('Digital price tag - Tag'),
	 ('Digital price tag - Tranceiver'),
	 ('Digital signage display'),
	 ('Dividing wall');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Dividing wall glazed'),
	 ('Docking station'),
	 ('Door glazed'),
	 ('Door one leaf'),
	 ('Door steel'),
	 ('Door wood'),
	 ('Download or upload 1 GB of data, via a fixed-line connection, end-user equipment not included FR'),
	 ('Download or upload 1 GB of data, via a mobile connection, end-user equipment not included FR'),
	 ('Drain'),
	 ('Drinking water water purification treatment production mix, at plant from groundwater RER');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Dual-flow ventilation'),
	 ('Duckboard'),
	 ('Duct'),
	 ('Edging'),
	 ('Electric cabinet'),
	 ('Electric convection heater'),
	 ('Electric panel'),
	 ('Electricity Mix Production mix Low voltage BE'),
	 ('Electricity Mix Production mix Low voltage CN'),
	 ('Electricity Mix Production mix Low voltage DE');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Electricity Mix Production mix Low voltage DK'),
	 ('Electricity Mix Production mix Low voltage FI'),
	 ('Electricity Mix Production mix Low voltage FR'),
	 ('Electricity Mix Production mix Low voltage NL'),
	 ('Electricity Mix Production mix Low voltage UE-27'),
	 ('Electricity Mix Production mix Low voltage UK'),
	 ('Electricity Mix Production mix Low voltage US'),
	 ('Emergency lighting unit'),
	 ('Empty 42U bay'),
	 ('External solid State Drive (SSD) 2,5, TLC, 1024 Go  production mix, at plant CN');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('External solid State Drive (SSD) 2,5, TLC, 2048 Go  production mix, at plant CN'),
	 ('External solid State Drive (SSD) 2,5, TLC, 256 Go  production mix, at plant CN'),
	 ('Extraction tower'),
	 ('False floor'),
	 ('Fan'),
	 ('Feature phone'),
	 ('Fence'),
	 ('Fence and barrier wire mesh'),
	 ('Fire detection station'),
	 ('Firewall');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Fixed-line network at consumer xDSL, FFTx average mix  EU-28'),
	 ('Fixed-line network at consumer xDSL, FFTx average mix  FR'),
	 ('Flexible covering'),
	 ('Flexicooling air conditioning cabinet'),
	 ('Flexicooling air conditioning crate'),
	 ('Frame'),
	 ('Generator 1136 kVA'),
	 ('Girder galvanized steel'),
	 ('Grid curtain wall'),
	 ('Hard disk drive mix of 2.5 and 3.5, mix of aluminium and glass disks');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Home console'),
	 ('IAD (Integrated Access Device) / CPE (Customer Premise Equipment) router'),
	 ('IAD router with ONT/SFP'),
	 ('IAD/CPE cable router'),
	 ('IAD/CPE router without ONT (Optical Network Termination) / SFP (Small Form-factor-Pluggable)'),
	 ('Impacts related to an IT department employee over a day FR'),
	 ('Impacts related to an employee over a day FR'),
	 ('Impacts related to one square meter of IT department office over a year FR'),
	 ('Impermeability'),
	 ('Insulation');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Insulation lining'),
	 ('Integrated tank'),
	 ('Interior light'),
	 ('Landline phone'),
	 ('Laptop 14.5 inches display, 1 CPU 126 mm² 14 nm lithography, 8 GB RAM, 564 GB SSD, integrated graphic card'),
	 ('Laptop 14.5 inches display, 1 CPU 156 mm² 7 nm lithography, 13 GB RAM, 427 GB SSD, integrated graphic card'),
	 ('Laptop 15.6 inches display, 1 CPU 126 mm² 14 nm lithography, 16 GB RAM, 512 GB SSD, separated graphic card 445 mm² 12 nm lithography'),
	 ('Lead battery 300 kVA'),
	 ('Lead battery 33 kVA'),
	 ('Lead battery 60 kVA');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Lift'),
	 ('Light'),
	 ('Light fuel oil at refinery from crude oil, fuel supply production mix, at refinery 0.1 wt.% sulphur EU-27'),
	 ('Light fuel oil combustion in 1 MW boiler consumption mix, at consumer RER'),
	 ('MME (Mobility Management Entity) /SGSN (Serving GPRS support node)'),
	 ('Mobile network at consumer 2G, 3G, 4G, 5G average mix  EU-28'),
	 ('Mobile network at consumer 2G, 3G, 4G, 5G average mix  FR'),
	 ('Motherboard mix of equipment, without processor or RAM'),
	 ('Motion sensor'),
	 ('Nozzle');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('OAN (Optical Access Node) and/or MDF (Main Distribution Frame ) site collection router/switch'),
	 ('OLED display panel, color'),
	 ('OLT (Optical Line Termination)'),
	 ('ONT (external)'),
	 ('Optical fibre – 12 strands'),
	 ('Optical fibre – 144 strands'),
	 ('Optical fibre – 2 strands'),
	 ('Optical fibre – 24 strands'),
	 ('Optical fibre – 288 strands'),
	 ('Optical fibre – 48 strands');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Optical fibre – 576 strands'),
	 ('Optical fibre – 72 strands'),
	 ('Optical fibre – 720 strands'),
	 ('Optical fibre – 96 strands'),
	 ('P-PE-Peering router'),
	 ('Paint'),
	 ('Paper production mix, at plant from virgin fiber'),
	 ('Paper production mix, at plant without deinking, 100% recycled, from waste paper'),
	 ('Passive multiband antenna (1.4m to 2.7m)'),
	 ('Perforated tiles');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Personnal laser printer'),
	 ('Photovoltaic panel mono 300 Wc'),
	 ('Plane technology mix, cargo 68 t payload RER'),
	 ('Portable console'),
	 ('Portal motorized'),
	 ('Post galvanized steel'),
	 ('Power socket'),
	 ('Power supply unit (PSU), computers, rack and mainframe servers input AC 100-240V, output DC 12V'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 101,83 mm² die area, 58 masks, 14 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 122,3 mm² die area, 58 masks, 14 nm photolithography');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 126 mm² die area, 58 masks, 14 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 131 mm² die area, 54 masks, 22 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 149.6 mm² die area, 58 masks, 14 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 174 mm² die area, 58 masks, 14 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 177mm² die area, 54 masks, 22 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 181mm² die area, 54 masks, 22 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 182 mm² die area, 58 masks, 14 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 246 mm² die area, 58 masks, 14 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 246,24mm² die area, 58 masks, 14 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 260mm² die area, 54 masks, 22 nm photolithography');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 306,18mm² die area, 58 masks, 14 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 325,44mm² die area, 58 masks, 14 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 355.52mm² die area, 54 masks, 22 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 456,12mm² die area, 58 masks, 14 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 485 mm² die area, 58 masks, 14 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 622 mm² die area, 54 masks, 22 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 694 mm² die area, 58 masks, 14 nm photolithography'),
	 ('Processor, DRAM, 2D and 3D NAND type semiconductor silicon substrate, PBGA/TFBGA/VFBGA encapsulation, 82 mm² die area, 58 masks, 14 nm photolithography'),
	 ('Professional laser printer'),
	 ('R134a leakage');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('R410a leakage'),
	 ('Rack server  1 processor high-end  1 SSD: 1024 GB each  0 HDD  16 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor high-end  1 SSD: 1024 GB each  0 HDD  2 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor high-end  1 SSD: 1024 GB each  0 HDD  2 RAM, 4 GB each  0 GPU'),
	 ('Rack server  1 processor high-end  1 SSD: 1024 GB each  0 HDD  24 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor high-end  1 SSD: 1024 GB each  0 HDD  48 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor high-end  1 SSD: 1024 GB each  0 HDD  48 RAM, 64 GB each  0 GPU'),
	 ('Rack server  1 processor high-end  1 SSD: 1024 GB each  0 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor high-end  4 SSD: 2048 GB each  0 HDD  16 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor high-end  4 SSD: 2048 GB each  0 HDD  2 RAM, 16 GB each  0 GPU');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Rack server  1 processor high-end  4 SSD: 2048 GB each  0 HDD  2 RAM, 4 GB each  0 GPU'),
	 ('Rack server  1 processor high-end  4 SSD: 2048 GB each  0 HDD  24 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor high-end  4 SSD: 2048 GB each  0 HDD  48 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor high-end  4 SSD: 2048 GB each  0 HDD  48 RAM, 64 GB each  0 GPU'),
	 ('Rack server  1 processor high-end  4 SSD: 2048 GB each  0 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor low-end  0 SSD: 0 GB each  1 HDD  2 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor low-end  0 SSD: 0 GB each  1 HDD  2 RAM, 4 GB each  0 GPU'),
	 ('Rack server  1 processor low-end  0 SSD: 0 GB each  1 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor low-end  0 SSD: 0 GB each  4 HDD  2 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor low-end  0 SSD: 0 GB each  4 HDD  2 RAM, 4 GB each  0 GPU');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Rack server  1 processor low-end  0 SSD: 0 GB each  4 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor low-end  1 SSD: 1024 GB each  0 HDD  2 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor low-end  1 SSD: 2048 GB each  0 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor low-end  2 SSD: 1024 GB each  0 HDD  2 RAM, 16 GB each  0 GPU'),
	 ('Rack server  1 processor low-end  2 SSD: 2048 GB each  0 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Rack server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  16 RAM, 16 GB each  0 GPU'),
	 ('Rack server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  16 RAM, 16 GB each  1 GPU'),
	 ('Rack server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  2 RAM, 16 GB each  0 GPU'),
	 ('Rack server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  2 RAM, 16 GB each  1 GPU'),
	 ('Rack server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  2 RAM, 4 GB each  0 GPU');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Rack server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  2 RAM, 4 GB each  1 GPU'),
	 ('Rack server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  24 RAM, 16 GB each  0 GPU'),
	 ('Rack server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  24 RAM, 16 GB each  1 GPU'),
	 ('Rack server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  48 RAM, 16 GB each  0 GPU'),
	 ('Rack server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  48 RAM, 16 GB each  1 GPU'),
	 ('Rack server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  48 RAM, 64 GB each  0 GPU'),
	 ('Rack server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  48 RAM, 64 GB each  1 GPU'),
	 ('Rack server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Rack server  2 processor high-end  1 SSD: 1024 GB each  0 HDD  8 RAM, 16 GB each  1 GPU'),
	 ('Rack server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  16 RAM, 16 GB each  0 GPU');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Rack server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  16 RAM, 16 GB each  1 GPU'),
	 ('Rack server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  2 RAM, 16 GB each  0 GPU'),
	 ('Rack server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  2 RAM, 16 GB each  1 GPU'),
	 ('Rack server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  2 RAM, 4 GB each  0 GPU'),
	 ('Rack server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  2 RAM, 4 GB each  1 GPU'),
	 ('Rack server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  24 RAM, 16 GB each  0 GPU'),
	 ('Rack server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  24 RAM, 16 GB each  1 GPU'),
	 ('Rack server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  48 RAM, 16 GB each  0 GPU'),
	 ('Rack server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  48 RAM, 16 GB each  1 GPU'),
	 ('Rack server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  48 RAM, 64 GB each  0 GPU');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Rack server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  48 RAM, 64 GB each  1 GPU'),
	 ('Rack server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  8 RAM, 16 GB each  0 GPU'),
	 ('Rack server  2 processor high-end  4 SSD: 2048 GB each  0 HDD  8 RAM, 16 GB each  1 GPU'),
	 ('Random-access memory, RAM DDR5, 128GB production mix, at plant CN'),
	 ('Random-access memory, RAM DDR5, 16GB production mix, at plant CN'),
	 ('Random-access memory, RAM DDR5, 2GB production mix, at plant CN'),
	 ('Random-access memory, RAM DDR5, 32GB production mix, at plant CN'),
	 ('Random-access memory, RAM DDR5, 4GB production mix, at plant CN'),
	 ('Random-access memory, RAM DDR5, 64GB production mix, at plant CN'),
	 ('Random-access memory, RAM DDR5, 8GB production mix, at plant CN');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Refrigerant production mix'),
	 ('Retaining wall'),
	 ('Retention reservoir'),
	 ('Ribbon'),
	 ('Road'),
	 ('SP-GW (Serving/PDN-Gateway)/GGSN (Gateway GPRS Support Node)'),
	 ('Search for an information with a search engine, consulting 2 pages of results, with a fixed-line connection, 50% desktop computer, 50% laptop computer FR'),
	 ('Search for an information with a search engine, consulting 2 pages of results, with a mobile connection, 15% tablet, 85% smartphone FR'),
	 ('Security Gateway 4G/5G'),
	 ('Self-contained emergency lighting unit');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Set top box'),
	 ('Set up a audioconference audio only, between 2 persons, with a fixed-line connection, laptop FR'),
	 ('Set up a audioconference audio only, between 2 persons, with a mobile connection, smartphone FR'),
	 ('Set up a audioconference audio only, between 20 persons, with a fixed-line connection, laptop FR'),
	 ('Set up a audioconference audio only, between 20 persons, with a mobile connection, smartphone FR'),
	 ('Set up a webconference between 2 persons, with a fixed-line connection, laptop FR'),
	 ('Set up a webconference between 2 persons, with a mobile connection, smartphone FR'),
	 ('Set up a webconference between 20 persons, with a fixed-line connection, laptop FR'),
	 ('Set up a webconference between 20 persons, with a mobile connection, smartphone FR'),
	 ('Shaft fan');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Siphon'),
	 ('Smartphone 6.57 inches display OLED, 1 CPU 101.66 mm² 8 nm lithography, 7 GB RAM, 160 GB SSD'),
	 ('Smartphone 6.59 inches display LCD, 1 CPU 101.66 mm² 12 nm lithography, 6 GB RAM, 128 GB SSD'),
	 ('Smartphone 6.72 inches display OLED, 1 CPU 101.66 mm² 7 nm lithography, 11 GB RAM, 341 GB SSD'),
	 ('Smoke detector'),
	 ('Solid State Drive (SSD) 2,5, MLC, 1024 Go  production mix, at plant CN'),
	 ('Solid State Drive (SSD) 2,5, MLC, 2048 Go  production mix, at plant CN'),
	 ('Solid State Drive (SSD) 2,5, MLC, 256 Go  production mix, at plant CN'),
	 ('Solid State Drive (SSD) 2,5, QLC, 1024 Go  production mix, at plant CN'),
	 ('Solid State Drive (SSD) 2,5, QLC, 2048 Go  production mix, at plant CN');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Solid State Drive (SSD) 2,5, QLC, 256 Go  production mix, at plant CN'),
	 ('Solid State Drive (SSD) 2,5, SLC, 1024 Go  production mix, at plant CN'),
	 ('Solid State Drive (SSD) 2,5, SLC, 2048 Go  production mix, at plant CN'),
	 ('Solid State Drive (SSD) 2,5, SLC, 256 Go  production mix, at plant CN'),
	 ('Solid State Drive (SSD) 2,5, TLC, 1024 Go  production mix, at plant CN'),
	 ('Solid State Drive (SSD) 2,5, TLC, 2048 Go  production mix, at plant CN'),
	 ('Solid State Drive (SSD) 2,5, TLC, 256 Go  production mix, at plant CN'),
	 ('Stairs concrete'),
	 ('Stairs galvanized steel'),
	 ('Storage bay  24 disks - HDD');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Storage bay  24 disks - MLC, 1024 GB'),
	 ('Storage bay  24 disks - MLC, 2048 GB'),
	 ('Storage bay  24 disks - MLC, 256 GB'),
	 ('Storage bay  24 disks - QLC, 1024 GB'),
	 ('Storage bay  24 disks - QLC, 2048 GB'),
	 ('Storage bay  24 disks - QLC, 256 GB'),
	 ('Storage bay  24 disks - SLC, 1024 GB'),
	 ('Storage bay  24 disks - SLC, 2048 GB'),
	 ('Storage bay  24 disks - SLC, 256 GB'),
	 ('Storage bay  24 disks - TLC, 1024 GB');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Storage bay  24 disks - TLC, 2048 GB'),
	 ('Storage bay  24 disks - TLC, 256 GB'),
	 ('Storage bay  48 disks - HDD'),
	 ('Storage bay  48 disks - MLC, 1024 GB'),
	 ('Storage bay  48 disks - MLC, 2048 GB'),
	 ('Storage bay  48 disks - MLC, 256 GB'),
	 ('Storage bay  48 disks - QLC, 1024 GB'),
	 ('Storage bay  48 disks - QLC, 2048 GB'),
	 ('Storage bay  48 disks - QLC, 256 GB'),
	 ('Storage bay  48 disks - SLC, 1024 GB');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Storage bay  48 disks - SLC, 2048 GB'),
	 ('Storage bay  48 disks - SLC, 256 GB'),
	 ('Storage bay  48 disks - TLC, 1024 GB'),
	 ('Storage bay  48 disks - TLC, 2048 GB'),
	 ('Storage bay  48 disks - TLC, 256 GB'),
	 ('Store in the cloud 1 GB of data, for 1 year, via a fixed-line connection, end-user equipment not included FR'),
	 ('Store in the cloud 1 GB of data, for 1 year, via a mobile connection, end-user equipment not included FR'),
	 ('Store in the cloud 1 GB of data, for 10 year, via a fixed-line connection, end-user equipment not included FR'),
	 ('Store in the cloud 1 GB of data, for 10 year, via a mobile connection, end-user equipment not included FR'),
	 ('Switch');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Switch/Router  12 ports per U  1 processors  48 GB RAM'),
	 ('Switch/Router  12 ports per U  2 processors  256 GB RAM'),
	 ('Switch/Router  16 ports per U  1 processors  512 GB RAM'),
	 ('Switch/Router  16 ports per U  1 processors  8 GB RAM'),
	 ('Switch/Router  24 ports per U  1 processors  2 GB RAM'),
	 ('Switch/Router  24 ports per U  1 processors  4 GB RAM'),
	 ('Switch/Router  24 ports per U  1 processors  512 GB RAM'),
	 ('Switch/Router  40 ports per U  1 processors  512 GB RAM'),
	 ('Switch/Router  48 ports per U  1 processors  16 GB RAM'),
	 ('Switch/Router  48 ports per U  1 processors  2 GB RAM');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Switch/Router  48 ports per U  1 processors  24 GB RAM'),
	 ('Switch/Router  48 ports per U  1 processors  4 GB RAM'),
	 ('Switch/Router  48 ports per U  1 processors  512 GB RAM'),
	 ('Switch/Router  64 ports per U  1 processors  16 GB RAM'),
	 ('Switch/Router  72 ports per U  1 processors  16 GB RAM'),
	 ('Switch/Router  72 ports per U  1 processors  4 GB RAM'),
	 ('Switch/Router  72 ports per U  1 processors  8 GB RAM'),
	 ('Switch/Router  8 ports per U  1 processors  32 GB RAM'),
	 ('Switch/Router  8 ports per U  1 processors  512 GB RAM'),
	 ('Switch/Router  8 ports per U  1 processors  8 GB RAM');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Switch/Router  8 ports per U  2 processors  32 GB RAM'),
	 ('TFT LCD display panel, color'),
	 ('Tablet 10.2 inches display LCD, 1 CPU 125 mm² 16 nm lithography, 4 GB RAM, 32 GB SSD'),
	 ('Tablet 10.3 inches display LCD, 1 CPU 125 mm² 16 nm lithography, 4 GB RAM, 256 GB SSD'),
	 ('Tablet 11.1 inches display LCD, 1 CPU 83,27 mm² 7 nm lithography, 6 GB RAM, 512 GB SSD'),
	 ('Television 45 inches, LCD'),
	 ('Television 53 inches, OLED'),
	 ('Television 68 inches, OLED'),
	 ('Tiling'),
	 ('Toner');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Train for freight transport technology mix electricity RER'),
	 ('Transformer 1250 kVA'),
	 ('Typical datacenter FR'),
	 ('Typical datacenter, architecture FR'),
	 ('Typical datacenter, non-IT equipment FR'),
	 ('USB key 128 GB capacity TLC'),
	 ('USB key 16 GB capacity TLC'),
	 ('USB key 32 GB capacity TLC'),
	 ('Under slab'),
	 ('Under-tile waterproofing system - SEL');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Under-tile waterproofing system - SPEC'),
	 ('Uninterruptible power supply (UPS) 300 kVA'),
	 ('Uninterruptible power supply (UPS) 33 KTL'),
	 ('Uninterruptible power supply (UPS) 60 KTL'),
	 ('Variable Refrigerant Volume (VRV), external unit'),
	 ('Variable Refrigerant Volume (VRV), internal unit'),
	 ('Video card, 1070 g, 302 cm² PWB, 251 mm² die, 75 mask layers, 7 nm lithography'),
	 ('Video card, 1280 g, 310 cm² PWB, 545 mm² die, 64 mask layers, 12 nm lithography'),
	 ('Video card, 1280 g, 310 cm² PWB, 754 mm² die, 64 mask layers, 12 nm lithography'),
	 ('Video card, 1370 g, 271 cm² PWB, 392 mm² die, 70 mask layers, 8 nm lithography');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Video card, 1520 g, 320 cm² PWB, 520 mm² die, 75 mask layers, 7 nm lithography'),
	 ('Video card, 1530 g, 319 cm² PWB, 628 mm² die, 70 mask layers, 8 nm lithography'),
	 ('Video card, 2040 g, 259 cm² PWB, 445 mm² die, 64 mask layers, 12 nm lithography'),
	 ('Video card, 298 g, 197 cm² PWB, 123 mm² die, 58 mask layers, 14 nm lithography'),
	 ('Video card, 501 g, 162 cm² PWB, 103 mm² die, 58 mask layers, 14 nm lithography'),
	 ('Video card, 590 g, 280 cm² PWB, 232 mm² die, 58 mask layers, 14 nm lithography'),
	 ('Video card, 814 g, 299 cm² PWB, 314 mm² die, 55 mask layers, 16 nm lithography'),
	 ('Video card, 865 g, 311 cm² PWB, 495 mm² die, 58 mask layers, 14 nm lithography'),
	 ('Video card, 875 g, 280 cm² PWB, 232 mm² die, 64 mask layers, 12 nm lithography'),
	 ('Video card, 898 g, 333 cm² PWB, 314 mm² die, 55 mask layers, 16 nm lithography');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Video card, 898 g, 333 cm² PWB, 471 mm² die, 55 mask layers, 16 nm lithography'),
	 ('Video card, 940 g, 337 cm² PWB, 232 mm² die, 58 mask layers, 14 nm lithography'),
	 ('Video card, 962 g, 316 cm² PWB, 158 mm² die, 75 mask layers, 7 nm lithography'),
	 ('Wafer substrat silicium 20 masques Chine'),
	 ('Wafer substrat silicium 20 masques EU-28'),
	 ('Wafer substrat silicium 20 masques FR'),
	 ('Wafer substrat silicium 20 masques TW'),
	 ('Wafer substrat silicium 29 masques, 130 nm photolithography Chine'),
	 ('Wafer substrat silicium 29 masques, 130 nm photolithography EU-28'),
	 ('Wafer substrat silicium 29 masques, 130 nm photolithography FR');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Wafer substrat silicium 29 masques, 130 nm photolithography TW'),
	 ('Wafer substrat silicium 33 masques, 90 nm photolithography Chine'),
	 ('Wafer substrat silicium 33 masques, 90 nm photolithography EU-28'),
	 ('Wafer substrat silicium 33 masques, 90 nm photolithography FR'),
	 ('Wafer substrat silicium 33 masques, 90 nm photolithography TW'),
	 ('Wafer substrat silicium 40 masques Chine'),
	 ('Wafer substrat silicium 40 masques EU-28'),
	 ('Wafer substrat silicium 40 masques FR'),
	 ('Wafer substrat silicium 40 masques TW'),
	 ('Wafer substrat silicium 42 masques, 45 nm photolithography Chine');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Wafer substrat silicium 42 masques, 45 nm photolithography EU-28'),
	 ('Wafer substrat silicium 42 masques, 45 nm photolithography FR'),
	 ('Wafer substrat silicium 42 masques, 45 nm photolithography TW'),
	 ('Wafer substrat silicium 50 masques, 28 nm photolithography Chine'),
	 ('Wafer substrat silicium 50 masques, 28 nm photolithography EU-28'),
	 ('Wafer substrat silicium 50 masques, 28 nm photolithography FR'),
	 ('Wafer substrat silicium 50 masques, 28 nm photolithography TW'),
	 ('Wafer substrat silicium 54 masques, 22 nm photolithography Chine'),
	 ('Wafer substrat silicium 54 masques, 22 nm photolithography EU-28'),
	 ('Wafer substrat silicium 54 masques, 22 nm photolithography FR');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Wafer substrat silicium 54 masques, 22 nm photolithography TW'),
	 ('Wafer substrat silicium 55 masques, 16 nm photolithography Chine'),
	 ('Wafer substrat silicium 55 masques, 16 nm photolithography EU-28'),
	 ('Wafer substrat silicium 55 masques, 16 nm photolithography FR'),
	 ('Wafer substrat silicium 55 masques, 16 nm photolithography TW'),
	 ('Wafer substrat silicium 58 masques, 14 nm photolithography Chine'),
	 ('Wafer substrat silicium 58 masques, 14 nm photolithography EU-28'),
	 ('Wafer substrat silicium 58 masques, 14 nm photolithography FR'),
	 ('Wafer substrat silicium 58 masques, 14 nm photolithography TW'),
	 ('Wafer substrat silicium 64 masques, 12 nm EUV lithography Chine');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Wafer substrat silicium 64 masques, 12 nm EUV lithography EU-28'),
	 ('Wafer substrat silicium 64 masques, 12 nm EUV lithography FR'),
	 ('Wafer substrat silicium 64 masques, 12 nm EUV lithography TW'),
	 ('Wafer substrat silicium 70 masques, 5 ou 8 nm EUV lithography Chine'),
	 ('Wafer substrat silicium 70 masques, 5 ou 8 nm EUV lithography EU-28'),
	 ('Wafer substrat silicium 70 masques, 5 ou 8 nm EUV lithography FR'),
	 ('Wafer substrat silicium 70 masques, 5 ou 8 nm EUV lithography TW'),
	 ('Wafer substrat silicium 75 masques, 7 nm EUV lithography Chine'),
	 ('Wafer substrat silicium 75 masques, 7 nm EUV lithography EU-28'),
	 ('Wafer substrat silicium 75 masques, 7 nm EUV lithography FR');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Wafer substrat silicium 75 masques, 7 nm EUV lithography TW'),
	 ('Wall, floor, ceiling coating wood'),
	 ('Wastewater network'),
	 ('Watch 1 hour of streaming video 1080p, 60 fps, via a fixed-line connection, 82% television, 18% laptop FR'),
	 ('Watch 1 hour of streaming video 1080p, 60 fps, via a mobile connection, 67% tablet, 33% smartphone FR'),
	 ('Watch 1 hour of streaming video 4k, 60 fps, via a fixed-line connection, 82% television, 18% laptop FR'),
	 ('Watch 1 hour of streaming video 4k, 60 fps, via a mobile connection, 67% tablet, 33% smartphone FR'),
	 ('Watch 1 hour of streaming video 720p, 30 fps, via a fixed-line connection, 82% television, 18% laptop FR'),
	 ('Watch 1 hour of streaming video 720p, 30 fps, via a mobile connection, 67% tablet, 33% smartphone FR'),
	 ('WiFi hotspot');
INSERT INTO opsian.NomComposant_M (nomComposant) VALUES
	 ('Wireless barcode scanner'),
	 ('Write, send and read an email 1MB size, to five recipient, with a fixed-line connection, 50% desktop computer, 50% laptop computer, 10-year storage with 3 redundancies on the sender and receiver sides FR'),
	 ('Write, send and read an email 1MB size, to five recipient, with a mobile connection, 15% tablet, 85% smartphone, 10-year storage with 3 redundancies on the sender and receiver sides FR'),
	 ('Write, send and read an email 1MB size, to one recipient, with a fixed-line connection, 50% desktop computer, 50% laptop computer, 10-year storage with 3 redundancies on the sender and receiver sides FR'),
	 ('Write, send and read an email 1MB size, to one recipient, with a mobile connection, 15% tablet, 85% smartphone, 10-year storage with 3 redundancies on the sender and receiver sides FR'),
	 ('Write, send and read an email 7kB size, to five recipient, with a fixed-line connection, 50% desktop computer, 50% laptop computer, 10-year storage with 3 redundancies on the sender and receiver sides FR'),
	 ('Write, send and read an email 7kB size, to five recipient, with a mobile connection, 15% tablet, 85% smartphone, 10-year storage with 3 redundancies on the sender and receiver sides FR'),
	 ('Write, send and read an email 7kB size, to one recipient, with a fixed-line connection, 50% desktop computer, 50% laptop computer, 10-year storage with 3 redundancies on the sender and receiver sides FR'),
	 ('Write, send and read an email 7kB size, to one recipient, with a mobile connection, 15% tablet, 85% smartphone, 10-year storage with 3 redundancies on the sender and receiver sides FR');
