version: "3"
services:
  react-app:
    build: ./client
    ports:
      - "3000:80"
  node-server:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - mysql-db
  mysql-db:
    build: ./Base_de_donnees
    environment:
      MYSQL_ROOT_PASSWORD: spocBDD
      MYSQL_DATABASE: opsian
      MYSQL_USER: numuser
      MYSQL_PASSWORD: spocBDD
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
