services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./Base_de_donnees/initDB.sql:/docker-entrypoint-initdb.d/0_initDB.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: opsian
      MYSQL_USER: numuser
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: spocBDD
      MYSQL_PASSWORD: spocBDD
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeserver:
    image: nodeapp:v1
    container_name: nodeservercontainer
    build: ./server
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - 4000:4000
    expose:
      - 4000
    environment:
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 4000

    depends_on:
      - mysqldb
    networks:
      - internalnet

  reactapp:
    image: nodeapp:v1
    container_name: reactappcontainer
    build: ./client
    volumes:
      - $HOME/reactapp:/code
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      SERVICE_TAGS: prod
      SERVICE_NAME: reactappservice
      SERVER_PORT: 3000

    depends_on:
      - nodeserver
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
